name: Prevent Merging from 2.x to main

on:
  pull_request:
    branches:
      - master

jobs:
  block-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block Merging from 2.x to main
        run: |
          if [[ "${{ github.head_ref }}" == "spring_boot_2x_branch" ]]; then
            echo "Merging 'spring boot 2.x branch' into 'main' is not allowed."
            exit 1
          fi
